### ISSUE TITLE
Support authentication for connecting to `scrapyd`

### ISSUE THREAD

**Issue by jwang-paradise** [mouday/spider-admin-pro#12]
Setting `scrapyd` authentication is crucial for safety. Please add support.

希望能添加对 scrapyd 帐户密码验证的支持。

可以在 YAML 配置文件中增加字段 `SCRAPYD_USERNAME` `SCRAPYD_PASSWORD`,
然后在 `service/scrapyd_service.py` 初始化 client 时添加 `auth` 参数即可:
```
from requests.auth import HTTPBasicAuth
client = ScrapydClient(base_url=SCRAPYD_SERVER,
                       auth=HTTPBasicAuth(SCRAPYD_USERNAME, BASCRAPYD_PASSWORD))
```

**Comment by mouday** [comment]
已收到反馈

**Comment by mouday** [comment]
v2.0.8 新增对 scrapyd 帐户密码basicauth验证的支持

```yaml
# 【可选】支持 basic auth @since 2.0.8 
SCRAPYD_USERNAME: ''
SCRAPYD_PASSWORD: ''
```
